import { User, Role } from './user';

export const USERS: User[] = [
  {
    firstName: 'Mr',
    middleName: 'Art',
    lastName: 'Marshall',
    email: 'art.marshall@example.com',
    phone: '016974 35276',
    role: Role.Admin,
    address: 'Highfield Road, Dundee, Cleveland - GG9 3SP',
  },
  {
    firstName: 'Mr',
    middleName: 'Mustafa',
    lastName: 'Gümüşpala',
    email: 'mustafa.gumuspala@example.com',
    phone: '(829)-801-0240',
    role: Role.Admin,
    address: 'Mevlana Cd, Muş, Antalya - 83013',
  },
  {
    firstName: 'Miss',
    middleName: 'Nurdan',
    lastName: 'Uluhan',
    email: 'nurdan.uluhan@example.com',
    phone: '(076)-123-4012',
    role: Role.Admin,
    address: 'Tunalı Hilmi Cd, Konya, Batman - 14370',
  },
  {
    firstName: 'Mr',
    middleName: 'Lewis',
    lastName: 'Carlson',
    email: 'lewis.carlson@example.com',
    phone: '(578)-935-2377',
    role: Role.Admin,
    address: 'Hogan St, Santa Maria, Colorado - 67387',
  },
  {
    firstName: 'Mr',
    middleName: 'Ivan',
    lastName: 'Reyes',
    email: 'ivan.reyes@example.com',
    phone: '996-075-898',
    role: Role.Admin,
    address: 'Calle de Toledo, Bilbao, Extremadura - 91589',
  },
  {
    firstName: 'Ms',
    middleName: 'Begüm',
    lastName: 'Pekkan',
    email: 'begum.pekkan@example.com',
    phone: '(761)-010-5882',
    role: Role.Admin,
    address: 'Abanoz Sk, Bartın, Zonguldak - 98721',
  },
  {
    firstName: 'Miss',
    middleName: 'Amy',
    lastName: 'Brar',
    email: 'amy.brar@example.com',
    phone: '792-667-5921',
    role: Role.Admin,
    address: '20th Ave, Chesterville, New Brunswick - U2A 8N1',
  },
  {
    firstName: 'Mrs',
    middleName: 'Jilke',
    lastName: 'Van Hunen',
    email: 'jilke.vanhunen@example.com',
    phone: '(745)-441-8071',
    role: Role.Admin,
    address: 'De Polle, Meeuwen, Overijssel - 84806',
  },
  {
    firstName: 'Miss',
    middleName: 'Vilma',
    lastName: 'Kujala',
    email: 'vilma.kujala@example.com',
    phone: '08-637-328',
    role: Role.Admin,
    address: 'Rautatienkatu, Alajärvi, Ostrobothnia - 61196',
  },
  {
    firstName: 'Mr',
    middleName: 'Xian',
    lastName: 'Schlepers',
    email: 'xian.schlepers@example.com',
    phone: '(455)-439-9718',
    role: Role.Admin,
    address: 'Habraken, Gorssel, Gelderland - 49254',
  },
  {
    firstName: 'Ms',
    middleName: 'Blanca',
    lastName: 'Crespo',
    email: 'blanca.crespo@example.com',
    phone: '943-159-387',
    role: Role.Admin,
    address: 'Calle de Alcalá, Orihuela, Región de Murcia - 18310',
  },
  {
    firstName: 'Mrs',
    middleName: 'Belinda',
    lastName: 'da Conceição',
    email: 'belinda.daconceicao@example.com',
    phone: '(23) 0964-7939',
    role: Role.Admin,
    address: 'Avenida da Legalidade, Valinhos, Mato Grosso - 31310',
  },
  {
    firstName: 'Mr',
    middleName: 'Gonzalo',
    lastName: 'Vicente',
    email: 'gonzalo.vicente@example.com',
    phone: '926-478-780',
    role: Role.Admin,
    address: 'Calle de La Almudena, Mérida, Castilla y León - 70427',
  },
  {
    firstName: 'Miss',
    middleName: 'Sofia',
    lastName: 'Jones',
    email: 'sofia.jones@example.com',
    phone: '(280)-848-2107',
    role: Role.Admin,
    address: 'Wainoni Road, Upper Hutt, Auckland - 61200',
  },
  {
    firstName: 'Mrs',
    middleName: 'Charline',
    lastName: 'Lecomte',
    email: 'charline.lecomte@example.com',
    phone: '03-46-50-43-23',
    role: Role.Admin,
    address: 'Rue du Château, Angers, Charente - 78035',
  },
  {
    firstName: 'Ms',
    middleName: 'Marie',
    lastName: 'Vincent',
    email: 'marie.vincent@example.com',
    phone: '05-19-87-11-82',
    role: Role.Admin,
    address: 'Montée Saint-Barthélémy, Aubervilliers, Loir-et-Cher - 91352',
  },
  {
    firstName: 'Mr',
    middleName: 'Roman',
    lastName: 'Spiller',
    email: 'roman.spiller@example.com',
    phone: '0958-5922415',
    role: Role.Admin,
    address: 'Amselweg, Selb, Brandenburg - 73807',
  },
  {
    firstName: 'Mr',
    middleName: 'Toivo',
    lastName: 'Lepisto',
    email: 'toivo.lepisto@example.com',
    phone: '07-087-089',
    role: Role.Admin,
    address: 'Siilitie, Ikaalinen, North Karelia - 91423',
  },
  {
    firstName: 'Mr',
    middleName: 'Leroy',
    lastName: 'Hill',
    email: 'leroy.hill@example.com',
    phone: '01-5985-9959',
    role: Role.Admin,
    address: 'E Center St, Melbourne, Queensland - 4963',
  },
  {
    firstName: 'Mrs',
    middleName: 'Virginia',
    lastName: 'Perez',
    email: 'virginia.perez@example.com',
    phone: '991-456-722',
    role: Role.Admin,
    address: 'Calle de Bravo Murillo, Murcia, Extremadura - 52680',
  },
  {
    firstName: 'Mr',
    middleName: 'Erik',
    lastName: 'Fuglestad',
    email: 'erik.fuglestad@example.com',
    phone: '29644245',
    role: Role.Admin,
    address: 'Holmenkollveien, Trømborg, Rogaland - 9100',
  },
  {
    firstName: 'Miss',
    middleName: 'Tugçe',
    lastName: 'Boersema',
    email: 'tugce.boersema@example.com',
    phone: '(228)-719-1814',
    role: Role.Admin,
    address: 'Carel Vosmaerdreef, Koewacht, Groningen - 60933',
  },
  {
    firstName: 'Mr',
    middleName: 'Dean',
    lastName: 'Ruiz',
    email: 'dean.ruiz@example.com',
    phone: '019467 44394',
    role: Role.Admin,
    address: 'King Street, Sunderland, Mid Glamorgan - M8Q 0XJ',
  },
  {
    firstName: 'Mr',
    middleName: 'Oliver',
    lastName: 'Sørensen',
    email: 'oliver.sorensen@example.com',
    phone: '53074935',
    role: Role.Admin,
    address: 'Hestehavevej, Gl. Rye, Midtjylland - 79801',
  },
  {
    firstName: 'Monsieur',
    middleName: 'Matteo',
    lastName: 'Renard',
    email: 'matteo.renard@example.com',
    phone: '078 103 55 27',
    role: Role.Admin,
    address: 'Route de Genas, Cheiry, Obwalden - 6087',
  },
  {
    firstName: 'Ms',
    middleName: 'Andrea',
    lastName: 'Rognerud',
    email: 'andrea.rognerud@example.com',
    phone: '60512389',
    role: Role.Admin,
    address: 'Ormsundveien, Brandal, Akershus - 3534',
  },
  {
    firstName: 'Mr',
    middleName: 'Dean',
    lastName: 'Holt',
    email: 'dean.holt@example.com',
    phone: '(173)-179-7545',
    role: Role.Admin,
    address: 'Mcgowen St, Elgin, Michigan - 45217',
  },
  {
    firstName: 'Miss',
    middleName: 'Ece',
    lastName: 'Çatalbaş',
    email: 'ece.catalbas@example.com',
    phone: '(887)-927-1852',
    role: Role.Admin,
    address: 'Istiklal Cd, Ankara, Antalya - 19273',
  },
  {
    firstName: 'Mrs',
    middleName: 'Johanne',
    lastName: 'Jørgensen',
    email: 'johanne.jorgensen@example.com',
    phone: '38386805',
    role: Role.Admin,
    address: 'Astrupvej, Argerskov, Midtjylland - 81823',
  },
  {
    firstName: 'Mr',
    middleName: 'Kasper',
    lastName: 'Wuori',
    email: 'kasper.wuori@example.com',
    phone: '09-566-715',
    role: Role.Admin,
    address: 'Hermiankatu, Pori, Central Finland - 84875',
  },
  {
    firstName: 'Mr',
    middleName: 'Darren',
    lastName: 'Owens',
    email: 'darren.owens@example.com',
    phone: '09-9933-2321',
    role: Role.Admin,
    address: 'Pecan Acres Ln, Australian Capital Territory, Queensland - 1482',
  },
  {
    firstName: 'Mr',
    middleName: 'ماهان',
    lastName: 'پارسا',
    email: 'mhn.prs@example.com',
    phone: '033-52594939',
    role: Role.Admin,
    address: 'شهید آرش مهر, خمینی‌شهر, کهگیلویه و بویراحمد - 89131',
  },
  {
    firstName: 'Mr',
    middleName: 'Tiago',
    lastName: 'Gauthier',
    email: 'tiago.gauthier@example.com',
    phone: '04-64-25-19-76',
    role: Role.Admin,
    address: 'Rue du Cardinal-Gerlier, Colombes, Dordogne - 48770',
  },
  {
    firstName: 'Miss',
    middleName: 'Sofia',
    lastName: 'Roberts',
    email: 'sofia.roberts@example.com',
    phone: '(615)-234-2615',
    role: Role.Admin,
    address: 'Otipua Road, Blenheim, Northland - 72594',
  },
  {
    firstName: 'Miss',
    middleName: 'Ida',
    lastName: 'Bowman',
    email: 'ida.bowman@example.com',
    phone: '09-4285-3700',
    role: Role.Admin,
    address: 'Blossom Hill Rd, Darwin, Australian Capital Territory - 8313',
  },
  {
    firstName: 'Ms',
    middleName: 'Jenny',
    lastName: 'Cruz',
    email: 'jenny.cruz@example.com',
    phone: '071-049-5735',
    role: Role.Admin,
    address: 'Killarney Road, Laytown-Bettystown-Mornington, Sligo - 40951',
  },
  {
    firstName: 'Ms',
    middleName: 'Tonya',
    lastName: 'Watson',
    email: 'tonya.watson@example.com',
    phone: '(797)-418-1223',
    role: Role.Admin,
    address: 'Pecan Acres Ln, Scurry, West Virginia - 97687',
  },
  {
    firstName: 'Madame',
    middleName: 'Antoinette',
    lastName: 'Adam',
    email: 'antoinette.adam@example.com',
    phone: '079 506 39 58',
    role: Role.Admin,
    address: 'Rue de Gerland, Genève, Zürich - 8560',
  },
  {
    firstName: 'Mr',
    middleName: 'Ilan',
    lastName: 'Rousseau',
    email: 'ilan.rousseau@example.com',
    phone: '01-68-08-21-74',
    role: Role.Admin,
    address: 'Avenue de la République, Rennes, Gers - 90139',
  },
  {
    firstName: 'Miss',
    middleName: 'Charlotte',
    lastName: 'Lambert',
    email: 'charlotte.lambert@example.com',
    phone: '02-18-79-27-11',
    role: Role.Admin,
    address: "Rue de L'Abbé-Roger-Derry, Nîmes, Haute-Corse - 80828",
  },
  {
    firstName: 'Mrs',
    middleName: 'Jessica',
    lastName: 'Peters',
    email: 'jessica.peters@example.com',
    phone: '011-068-3120',
    role: Role.Admin,
    address: 'Grove Road, Ardee, Limerick - 28027',
  },
  {
    firstName: 'Mr',
    middleName: 'Giray',
    lastName: 'Adan',
    email: 'giray.adan@example.com',
    phone: '(264)-216-7501',
    role: Role.Admin,
    address: 'Maçka Cd, Iğdır, Bayburt - 18214',
  },
  {
    firstName: 'Mr',
    middleName: 'Oscar',
    lastName: 'Herrero',
    email: 'oscar.herrero@example.com',
    phone: '978-342-183',
    role: Role.Admin,
    address: 'Calle de Pedro Bosch, Zaragoza, Galicia - 51039',
  },
  {
    firstName: 'Ms',
    middleName: 'Goverdina',
    lastName: 'Braas',
    email: 'goverdina.braas@example.com',
    phone: '(185)-595-6768',
    role: Role.Admin,
    address: 'Cantate, Deinum, Groningen - 42688',
  },
  {
    firstName: 'Ms',
    middleName: 'Veera',
    lastName: 'Marttila',
    email: 'veera.marttila@example.com',
    phone: '05-576-252',
    role: Role.Admin,
    address: 'Itsenäisyydenkatu, Salla, Pirkanmaa - 73861',
  },
  {
    firstName: 'Mr',
    middleName: 'Eemeli',
    lastName: 'Toro',
    email: 'eemeli.toro@example.com',
    phone: '07-719-907',
    role: Role.Admin,
    address: 'Korkeavuorenkatu, Jomala, South Karelia - 32403',
  },
  {
    firstName: 'Mrs',
    middleName: 'Margaux',
    lastName: 'Bernard',
    email: 'margaux.bernard@example.com',
    phone: '01-91-27-39-96',
    role: Role.Admin,
    address: 'Avenue des Ternes, Mulhouse, Haut-Rhin - 32138',
  },
  {
    firstName: 'Mr',
    middleName: 'Oskari',
    lastName: 'Rintala',
    email: 'oskari.rintala@example.com',
    phone: '08-197-864',
    role: Role.Admin,
    address: 'Nordenskiöldinkatu, Geta, Päijät-Häme - 48555',
  },
  {
    firstName: 'Mr',
    middleName: 'كيان',
    lastName: 'حسینی',
    email: 'kyn.hsyny@example.com',
    phone: '048-67745675',
    role: Role.Admin,
    address: 'نبرد, اهواز, گلستان - 91856',
  },
  {
    firstName: 'Mr',
    middleName: 'Charles',
    lastName: 'Patel',
    email: 'charles.patel@example.com',
    phone: '930-342-4501',
    role: Role.Admin,
    address: 'St. Lawrence Ave, Red Rock, Nunavut - L4J 8N5',
  },
];
